[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

# Handle all routes - simple redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimize static assets
[[headers]]
  for = "/static/*"
  values = { Cache-Control = "public, max-age=31536000, immutable" }

[[headers]]
  for = "/_next/static/*"
  values = { Cache-Control = "public, max-age=31536000, immutable" }

[[headers]]
  for = "/*"
  values = { Referrer-Policy = "strict-origin-when-cross-origin", X-Content-Type-Options = "nosniff", X-Frame-Options = "DENY", X-XSS-Protection = "1; mode=block" }

[[headers]]
  for = "/images/*"
  values = { Cache-Control = "public, max-age=2592000" }
